<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.budaos</groupId>
        <artifactId>QuickBlue-MicroAI</artifactId>
        <version>4.0.0</version>
    </parent>

    <artifactId>QuickBlue-common</artifactId>
    <packaging>pom</packaging>

    <name>QuickBlue Common</name>
    <description>QuickBlue 公共模块</description>

    <modules>
        <module>QuickBlue-common-core</module>
        <module>QuickBlue-common-security</module>
        <module>QuickBlue-common-database</module>
        <module>QuickBlue-common-redis</module>
        <module>QuickBlue-common-swagger</module>
        <module>QuickBlue-common-web</module>
        <module>QuickBlue-common-log</module>
        <module>QuickBlue-common-excel</module>
    </modules>
</project>
